import json
from pathlib import Path

import duckdb
import xmltodict

BASE_DIR = Path(__file__).resolve().parent
db_path = BASE_DIR / "data_archival.db"
xml_file_path = BASE_DIR / "document.xml"




def archive_xml_as_json():
    # 1. Load and parse the XML into a Python Dictionary
    with open(xml_file_path, encoding="utf-8") as f:
        parsed_dict = xmltodict.parse(f.read())

    # Extract Root & Sub-nodes safely
    root = parsed_dict.get("inport-metadata", {})
    item_id_node = root.get("item-identification", {})
    keywords_node = root.get("keywords", {}).get("keyword", [])

    # 2. Extract Metadata Fields
    # Extraction A: Creation Date
    creation_date = item_id_node.get("creation-date")

    # Extraction B: Keywords List
    # Handles single item vs array structure generated by xmltodict
    keywords_list = []
    if isinstance(keywords_node, dict):
        keywords_node = [keywords_node]

    for k in keywords_node:
        word = k.get("keyword")
        if word:
            keywords_list.append(word)

    # 3. Serialize full payload to JSON string
    json_payload = json.dumps(parsed_dict)

    # 4. Ingest directly into DuckDB
    with duckdb.connect(str(db_path)) as con:

        # Insert metadata into 'files' table
        con.execute(
            """
            INSERT INTO files (
                file_id,
                category_id,
                file_name,
                file_type,
                keywords,
                created_at
            )
            
            VALUES (?, ?, ?, ?, ?, ?);
        """,
            [
                201,
                1,
                xml_file_path.name,
                "XML-InPort",
                keywords_list,
                creation_date,
            ],
        )

        # Insert raw JSON payload into 'sample_datasets'
        con.execute(
            """
            INSERT INTO sample_datasets (
                sample_id,
                file_id,
                sample_data
            )

            VALUES (?, ?, ?::json);
        """,
            [501, 201, json_payload],
        )

    print(
        f"Successfully archived {xml_file_path.name} as structured JSON and extracted {len(keywords_list)} keywords!"
    )


if __name__ == "__main__":
    archive_xml_as_json()
    